parameters:
#    sopinet_upload_magic.example.class: Sopinet\UploadMagicBundle\Example

services:
    sopinet.uploadlistener:
        class: Sopinet\Bundle\UploadMagicBundle\Listener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
